name: Deploy

on:
  push:
    branches-ignore:
      - source
  repository_dispatch:
    types: [deploy-website-staging]

env:
  GATSBY_HAYSTACK_HUB_TOKEN: ${{ secrets.HAYSTACK_HUB_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Build
        run: |
          npm install
          githubRef=$(echo '${{ github.event.client_payload.ref }}' | sed 's/refs\/heads\///g')
          echo $githubRef
          [[ ! -z "${githubRef}" ]] && npm run update_img_dev $githubRef || npm run update_img_dev master
          [[ ! -z "${githubRef}" ]] && npm run update_apidocs_dev $githubRef || npm run update_apidocs_dev master
          [[ ! -z "${githubRef}" ]] && npm run update_tutorialsdocs_dev $githubRef || npm run update_tutorialsdocs_dev master
          [[ ! -z "${githubRef}" ]] && npm run update_usagedocs_dev $githubRef || npm run update_usagedocs_dev master
          [[ ! -z "${githubRef}" ]] && npm run update_benchmarks_dev $githubRef || npm run update_benchmarks_dev master
          npm ci
          npm run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Deploy
        uses: jonelantha/gatsby-s3-action@v1-debug
        with:
          dest-s3-bucket: haystackhub-website
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - name: Check links
        run: |
          npm install broken-link-checker -g
          npm install sitemap-urls
          npm run check_links_dev
